### PR TITLE
Add setLockTime to TransactionBuilder

### PR DESCRIPTION
**Pull request by rcawston**

### CODE REVIEW

**Comment by cgcardona** [comment]
This looks great! Thank you!

Can you add a test and we can ship this.

**Comment by rcawston** [comment]
Sure - will try to find some time to build a few test cases soon.

**Comment by rcawston** [comment]
Test cases added

**Comment by cgcardona** [comment]
@GitCash send $1 to @rcawston

Thank you!

**Comment by GitCash** [comment]
Hey **rcawston**, user **cgcardona** tipped you **6329 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/rcawston)*

You can also add the "thumbs down" reaction to **cgcardona**'s comment above to prevent future tips.

**Pull request merged**
