### PR TITLE
more small fixes

### PR DESCRIPTION
**Pull request by deepthawtz**
* some small fixes to prevent people from doing idiotic things
* added flag parser helper method
* .nvmrc file

### CODE REVIEW

**Comment by cgcardona** [comment]
Nice. Thanks!

@gitcash 132652 satoshis to @deepthawtz

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/deepthawtz)
@deepthawtz

**Comment by deepthawtz** [comment]
@GitCash send 321 bits to @cgcardona

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/cgcardona)
@cgcardona

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @jbdtky

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/jbdtky)
@jbdtky

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @sagech

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/sagech)
@sagech

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @zowki

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/zowki)
@zowki

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @maplesyrupsucker

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/maplesyrupsucker)
@maplesyrupsucker

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @magmahindenburg

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/magmahindenburg)
@magmahindenburg

**Comment by cgcardona** [comment]
@GitCash 129816 satoshis to @jelaludo

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/jelaludo)
@jelaludo

**Pull request merged**
